spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root123456_
    url: jdbc:mysql://47.98.129.40:3306/car_repair?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB #单个数据大小
      max-request-size: 100MB #总数据大小

server:
  servlet:
    context-path: /car-repair


